# Generated by Django 4.2 on 2023-06-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='event_images')),
                ('date', models.DateField()),
                ('theme', models.CharField(choices=[('festival', 'Festival'), ('theatre', 'Théâtre'), ('soiree_musicale', 'Soirée Musicale'), ('sport', 'Sport')], max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pays', models.CharField(default='Your Default Country', max_length=100)),
                ('ville', models.CharField(default='Your Default Country', max_length=100)),
            ],
        ),
    ]
